twitter: ""
github: "https://github.com/TimSamuelsen"
instagram: "https://www.instagram.com/tim.samuelsen/"
linkedin: "https://linkedin.com/in/timsamuelsen"
dribbble: ""
youtube: ""
facebook: ""
medium: ""
patreon: ""
paypal: ""
unsplash: ""
